package FlowchartLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_TimeType extends EnumerationDescriptorBase {

  public EnumerationDescriptor_TimeType() {
    super(0xae0eef6aa0ca474eL, 0x9247c32571221195L, 0x51b93ed195e53aebL, "TimeType", "r:d21c3985-4ff8-4bc8-acbd-041fc47620f8(FlowchartLanguage.structure)/5888807057647549163");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_second_0 = new EnumerationDescriptor.MemberDescriptor("second", "sec", 0x51b93ed195e53aecL, "r:d21c3985-4ff8-4bc8-acbd-041fc47620f8(FlowchartLanguage.structure)/5888807057647549164");
  private final EnumerationDescriptor.MemberDescriptor myMember_minute_0 = new EnumerationDescriptor.MemberDescriptor("minute", "min", 0x51b93ed195e53aedL, "r:d21c3985-4ff8-4bc8-acbd-041fc47620f8(FlowchartLanguage.structure)/5888807057647549165");
  private final EnumerationDescriptor.MemberDescriptor myMember_hour_0 = new EnumerationDescriptor.MemberDescriptor("hour", "hr", 0x51b93ed195e53af0L, "r:d21c3985-4ff8-4bc8-acbd-041fc47620f8(FlowchartLanguage.structure)/5888807057647549168");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xae0eef6aa0ca474eL, 0x9247c32571221195L, 0x51b93ed195e53aebL, 0x51b93ed195e53aecL, 0x51b93ed195e53aedL, 0x51b93ed195e53af0L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_second_0, myMember_minute_0, myMember_hour_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_second_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "second":
        return myMember_second_0;
      case "minute":
        return myMember_minute_0;
      case "hour":
        return myMember_hour_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
