package FlowchartLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Body = 0;
  public static final int Decision = 1;
  public static final int DecisionTransmission = 2;
  public static final int Delay = 3;
  public static final int EmptyStatement = 4;
  public static final int End = 5;
  public static final int FlowChart = 6;
  public static final int Procedure = 7;
  public static final int ProcedureTransmission = 8;
  public static final int Start = 9;
  public static final int Statement = 10;
  public static final int StatementTransmission = 11;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xae0eef6aa0ca474eL, 0x9247c32571221195L);
    builder.put(0x51b93ed195e1997bL, Body);
    builder.put(0x51b93ed195d33612L, Decision);
    builder.put(0x51b93ed195e4bcf9L, DecisionTransmission);
    builder.put(0x51b93ed195ded53aL, Delay);
    builder.put(0x51b93ed195e74e15L, EmptyStatement);
    builder.put(0x51b93ed195ddfd8fL, End);
    builder.put(0x66267d1598c0f0ddL, FlowChart);
    builder.put(0x51b93ed195d52992L, Procedure);
    builder.put(0x51b93ed195d5cd2aL, ProcedureTransmission);
    builder.put(0x51b93ed195dd2abbL, Start);
    builder.put(0x51b93ed195d0d89bL, Statement);
    builder.put(0x51b93ed195d831f5L, StatementTransmission);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
